version: "3.8"
services:
  db:
    container_name: geo_postgis
    image: "postgis/postgis:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@word1
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    # healthcheck:
      # test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      # interval: 30s
      # timeout: 10s
      # retries: 5
    volumes:
      - type: bind
        source: /mnt/2TB_ssd/postgres-data
        target: /var/lib/postgresql/data
    # volumes:
    #  - /mnt/2TB_ssd/postgres-data:/var/lib/postgresql/data

